// react-frontend/src/features/memories/components/image-upload/image-upload.tsx
import { useRef, useState } from 'react';
import './styles.css';

const ImageUpload = ({
    imageAdded
}: {
    imageAdded: (file: File) => any;
}) => {
    const [isHovered, setIsHovered] = useState<boolean>(false);
    const [imageUrl, setImageUrl] = useState<string>();
    const fileInput = useRef<any>(null);
    const handleDragOver = (event: any) => {
        event.preventDefault();
        setIsHovered(true);
    };

    const handleDragOut = (event: any) => {
        event.preventDefault();
        setIsHovered(false);
    };

    const handleDrop = (event: any) => {
        event.preventDefault();
        try{
            if(event.dataTransfer.items.length > 0){
                const file = event.dataTransfer.items[0].getAsFile();
                //url for image preview
                const url = URL.createObjectURL(file);
                console.log(url);
                setImageUrl(url);
                imageAdded(file);
            }
        }
        catch(e){
            console.warn(e);
        }
    };

    const handleImageSelected = (event: any) => {
        const files = event.target.files;
        if(files.length > 0){
            const file = files[0];
            const url = URL.createObjectURL(file);
            console.log(url);
            setImageUrl(url);
            imageAdded(file);
        }
    }

    return (
        <div className="upload-container">
            <div
            className={`drop-file clickable ${isHovered ? 'file-hovered' : ''}`}
            onDragOver={(e) => handleDragOver(e)}
            onDragLeave={(e) => handleDragOut(e)}
            onMouseLeave={(e) => handleDragOut(e)}
            onDrop={(e) => handleDrop(e)}
            onClick={(e) => fileInput?.current ? fileInput.current.click() : null}>
                <div className="drop-description">
                    <span>
                        Drag and drop a file or click here to select a image
                    </span>
                </div>
            </div>
            <div className="hidden">
                <input
                ref={fileInput}
                type="file" 
                className="custom-file-input"
                onChange={(e) => handleImageSelected(e)}/>
            </div>
        </div>
    )
}

export default ImageUpload;

// frontend/src/app/modules/memories/components/image-upload/image-upload.component.ts
import { Component, Input, OnInit } from '@angular/core';

@Component({
  selector: 'app-image-upload',
  templateUrl: './image-upload.component.html',
  styleUrls: ['./image-upload.component.css']
})
export class ImageUploadComponent implements OnInit {
  @Input() image: string = null;

  isDraggedOver: boolean = false;

  constructor() { }

  ngOnInit(): void {
  }

  handleImageSelected(files: FileList){
    if(files.length > 0){
      const file = files[0];
      const url = URL.createObjectURL(file)
      this.image = url;
    }
  }

  handleImageDropped(event: any){
    console.log(event.dataTransfer.items);
    event.preventDefault();
    if(event?.dataTransfer?.items.length > 0){
      try{
        const file = event.dataTransfer.items[0].getAsFile();
        const url = URL.createObjectURL(file)
        this.image = url;
      }
      catch(e){
        console.warn(e);
      }
    }
  }

  handleDragOver(event:any){
    event.preventDefault();
    this.isDraggedOver = true
  }

  handleDragOut(){
    this.isDraggedOver = false;
  }
}

<div class="upload-container">
    <ng-container *ngIf="!image">
        <div
        [ngClass]="{
            'drop-file':true, 
            'clickable':true,
            'dragged-over':isDraggedOver
        }"
        (dragover)="handleDragOver($event)"
        (mouseleave)="handleDragOut()"
        (dragleave)="handleDragOut()"
        (drop)="handleImageDropped($event)"
        (click)="uploadInput.click()">
            <div class="drop-description">
                <span>
                    Drag and drop a file or click here to select a image
                </span>
            </div>
        </div>
        <div class="input-group mb-3 upload">
            <div class="input-group-prepend">
              <span class="input-group-text">Upload Image</span>
            </div>
            <div class="custom-file">
                <input 
                #uploadInput
                (change)="handleImageSelected($event.target.files)" 
                type="file" 
                class="custom-file-input">
                <label 
                class="custom-file-label">
                    No File Selected
                </label>
            </div>
        </div>
    </ng-container>
    <ng-containg *ngIf="image">
        <app-memory-image [image]="image"></app-memory-image>
    </ng-containg>
</div>
